Rails.application.routes.draw do
  get 'games/g0'
  get 'games/g1'
  get 'games/g2'
  get 'games/g3'
  get 'games/g4'
  get 'games/g5'
  get 'games/g6'
  get 'games/g7'
  get 'games/g8'
  get 'games/g9'
  get 'games/g10'
  get 'games/g11'
  get 'games/g12'
  get 'games/g13'
  get 'games/g14'
  get 'games/g15'
  get 'games/g16'
  get 'games/g17'
  get 'games/g18'
  get 'games/g19'
  get 'games/g20'
  get 'games/g21'
  get 'games/g22'
  get 'games/g23'
  get 'games/g24'
  get 'games/g25'
  get 'games/g26'
  get 'games/g27'
  get 'games/g28'
  get 'games/g29'
  get 'games/g30'
  get 'games/g31'
  get 'games/g32'
  get 'games/g33'
  get 'games/g34'
  get 'games/g35'
  get 'games/g36'
  get 'categories/zapusk'
  get 'categories/obstezhennya'
  get 'categories/avtomatyzacia'
  get 'categories/dyfretciacia'
  get 'categories/other'
  get 'categories/video'
  devise_for :users
  root 'pages#index', as: 'home'
  get 'about' => 'pages#about'
  get 'rules' => 'pages#rules'
  get 'shop' => 'pages#shop'
  get 'contacts' => 'pages#contacts'
  get 'freegames' => 'pages#freegames'
  resources :posts
end
